### ISSUE TITLE
Flow: cannot resolve module react-native-email-link

### ISSUE THREAD

**Issue by SonQBChau** [leanmotherfuckers/react-native-email-link#12]
Flow and eslint would not recognize the module.
It's not a bug, everything is running fine but it would be nice to have it fixed.

Current version:
React-native: 0.57
eslint: 5.6.1
flow: 0.78

**Comment by tschoffelen** [comment]
I'm not really using Flow a lot. Any chance you could suggest a fix?

**Comment by flexbox** [comment]
@SonQBChau Do you think you can close this issue?
Because the entire industry is migratinf to TypeScript now :)

**Comment by sprotymo** [comment]
You can use:
 flow-typed create-stub react-native-email-link

**Comment by jakallergis** [comment]
I get the exact same thing and I'm no TypeScript (RN 0.63)
