### ISSUE TITLE
License File

### ISSUE THREAD

**Issue by ball-hayden** [leanmotherfuckers/react-native-email-link#17]
Good day.

Thanks for the great library. I notice you have set the license for this package to `MIT` in `package.json`, but haven't included a `LICENSE` or `COPYING` file in the repo.

Please can you confirm this library is indeed licensed under the MIT license, and consider adding the license to the repo?

**Comment by tschoffelen** [comment]
It is indeed MIT licensed.

Added a license file in https://github.com/leanmotherfuckers/react-native-email-link/commit/632db1d504e020607150308b72a075f0793bc04d

Thanks!

**Comment by ball-hayden** [comment]
Thanks for your prompt response 🙂
