### ISSUE TITLE
[Android] Attempt to invoke virtual method 'int android.content.Intent.getFlags()' on a null object reference

### ISSUE THREAD

**Issue by mk-nickyang** [leanmotherfuckers/react-native-email-link#20]
Hi, this library works perfectly on most Android devices, but when I tested it on a Galaxy S6 with Android 5, it crashed. Here's the stack trace I got
```
java.lang.NullPointerException Attempt to invoke virtual method 'int android.content.Intent.getFlags()' on a null object reference 
    Intent.java:891 android.content.Intent.createChooser
    EmailModule.java:42 com.facebook.react.modules.email.EmailModule.open
    Method.java:-2 java.lang.reflect.Method.invoke
    Method.java:372 java.lang.reflect.Method.invoke
    JavaMethodWrapper.java:372 com.facebook.react.bridge.JavaMethodWrapper.invoke
    JavaModuleWrapper.java:160 com.facebook.react.bridge.JavaModuleWrapper.invoke
    NativeRunnable.java:-2 com.facebook.react.bridge.queue.NativeRunnable.run
    Handler.java:739 android.os.Handler.handleCallback
    Handler.java:95 android.os.Handler.dispatchMessage
    MessageQueueThreadHandler.java:29 com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage
    Looper.java:145 android.os.Looper.loop
    MessageQueueThreadImpl.java:192 com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run
    Thread.java:818 java.lang.Thread.run
```

I also experienced the similar crashes when I test it on some Android Emulators with Android 7 (API version 25) or earlier

[![Image from Gyazo](https://i.gyazo.com/f845d6f37c80f3828552df6a3b0aa1fe.png)](https://gyazo.com/f845d6f37c80f3828552df6a3b0aa1fe)

---
My code:
```
import { openInbox } from "react-native-email-link";
...
<Button
    onPress={() => openInbox()}
    title="Open Email App"
/>
...
```

My environment:
```
"react-native": "0.57.0",
"react": "16.5.0",
"react-native-email-link": "^1.2.1",
```

**Comment by tschoffelen** [comment]
@RBogie any chance you could have a look at this some time next week? I noticed we are also getting similar crash reports for our own app (Hoy).

Thanks!

**Comment by jorisw** [comment]
Same error here, on Android only.

```
        buildToolsVersion = "27.0.3"
        minSdkVersion = 16
        compileSdkVersion = 27
        targetSdkVersion = 26
        supportLibVersion = "27.0.3"
```

```
    "react": "16.6.0-alpha.8af6728",
    "react-native": "0.57.3",
    "react-native-email-link": "^1.2.3",
```

**Comment by johnnyborg** [comment]
Yeah, we've got this issue too. Its however not an issue on the line state @jorisw but a bit lower. Android on lower SDKs has an com.android.fallback package which has no default intent, causing the null pointer exception. 

I've written an fix for this. @tschoffelen can you integrate it? 
https://github.com/leanmotherfuckers/react-native-email-link/pull/24

**Comment by tschoffelen** [comment]
Thanks @johnnyborg, that's great! I've incorporated your fix into the latest NPM release (`react-native-email-link@1.4.0`).

**Comment by johnnyborg** [comment]
Awesome, @tschoffelen . Bedankt ;-)!
