### ISSUE TITLE
Question: open mail app with predefined email?

### ISSUE THREAD

**Issue by oferRounds** [leanmotherfuckers/react-native-email-link#22]
Hi, thank you for this library! Looks good!

Can I use it open the mail app with a predefined email?

**Comment by tschoffelen** [comment]
Hi,

No, at the moment this library is only able to show the user's inbox screen.

**Comment by oferRounds** [comment]
Got you, thanks!

**Comment by cesar3030** [comment]
@oferRounds I've created a PR #31 to add this feature to this awesome library. For now it's only working on iOS. Feel free to help implementing the Android part :)

**Comment by oferRounds** [comment]
Wow! Awesome! way to go
Will try to look into Android

Thanks for remembering!

**Comment by cesar3030** [comment]
Thank you very much!

**Comment by liushijie686** [comment]
@cesar3030 Hello, Android. Is that ok？
