### ISSUE TITLE
README.md doesn't describe options

### ISSUE THREAD

**Issue by mvanroon** [leanmotherfuckers/react-native-email-link#7]
Great util guys. I just noticed that the options that can be supplied to openInbox() aren't in the readme

**Comment by mvanroon** [comment]
Just found this old issue, heh :)

I can pick this up myself if you like. Should we make the options optional? Neither ActionSheetIOS nor the Android native module require a title.

**Comment by tschoffelen** [comment]
For usability, I would just keep the default ones if no/empty values are specified. Although a title isn't required, a ActionSheet with only the names of the email clients might not be the clearest thing in the world.

**Comment by mvanroon** [comment]
- You click 'open email'
 - a list of email client shows up
 - the title reads 'open email'
 - the message reads 'please pick an email client'

might be a bit too much if you ask me - but I'll settle for just making the options.message optional. Is that something that you can live with? 😸

**Comment by tschoffelen** [comment]
Haha, agreed. I think we can even remove the default value for message. Title is indeed more than enough.
